# Buildspec that copies the contents of bitbucket repo to s3 bucket
version: 0.2

phase:
  prebuild:
    commands:
      - echo list s3 buckets
      - aws s3 ls
  
  build:
    commands:
      - echo copy files to s3
      - for i in $(aws s3 ls | awk '{print $3}'); do echo $i; if [ $i = $S3_BUCKET_NAME ]; 
        then echo "Bucket exists" && aws s3 cp --recursive . s3://$S3_BUCKET_NAME; fi; done
      - echo list s3 buckets
      - aws s3 ls
      - echo list s3 bucket contents
      - aws s3 ls s3://$S3_BUCKET_NAME

  post_build:
    commands:
      - echo "Build completed on `date`"
      
